# Generated by Django 5.2.4 on 2025-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
    ]
