# Generated by Django 5.2.4 on 2025-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='questions_per_cycle',
            field=models.PositiveIntegerField(default=5, help_text='Number of questions to ask in each survey cycle'),
        ),
    ]
