# Generated by Django 5.2.4 on 2025-07-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_questions_per_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='organizations.organizationmembership'),
        ),
    ]
