# Generated by Django 5.2.4 on 2025-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='title',
            field=models.CharField(blank=True, help_text='Job title or position', max_length=100),
        ),
    ]
